### ISSUE TITLE
Agree on /results endpoint interface

### ISSUE THREAD

**Issue by basti-n** [basti-n/tic-tac-toe#3]
@miriamhaenle 

Endpoint: /result 
[POST]
`interface GameStatus {
  game: {
    0: 'o' | 'x' | null;
    1: 'o' | 'x' | null;
    2: 'o' | 'x' | null;
    3: 'o' | 'x' | null;
    4: 'o' | 'x' | null;
    5: 'o' | 'x' | null
    6: 'o' | 'x' | null;
    7: 'o' | 'x' | null;
    8: 'o' | 'x' | null;
  },
  completed: boolean;
  winner?: 'x' | 'o';
}`

**Comment by miriamhaenle** [comment]
Please adjust the endpoint to return both value and id in the game property: 
`   game: [
      { value: null, id: 'top-left' },
      { value: null, id: 'top-middle' },
      { value: 'x', id: 'top-rigth' },
      { value: null, id: 'middle-left' },
      { value: null, id: 'middle-middle' },
      { value: 'o', id: 'middle-rigth' },
      { value: null, id: 'bottom-left' },
      { value: null, id: 'bottom-middle' },
      { value: 'x', id: 'bottom-rigth' },
    ],
    completed: false,
    winner: null,`
